import { Dealer, Model, DealerModel, BlogPost } from '../types';

// Data derived from CSV files
export const initialDealers: Dealer[] = [
    { id: "1", name: "Connect Drive (BYD Electric Cars Albania)", address: "Siri Kodra Street, Tirana, Albania", city: "Tirana", lat: 41.3389, lng: 19.8245, phone: "+355 69 941 4270", email: "info@connectgroup.al", website: "https://connectdrive.al", social_links: { instagram: "@connectdrive_byd", facebook: "Facebook" }, brands: ["BYD"], modelsAvailable: ["BYD Atto 3", "BYD Dolphin", "BYD Han EV", "BYD Song", "BYD Seagull", "BYD Sealion", "BYD Yuan"], typeOfCars: "New (custom orders)", languages: ["Albanian", "English"], notes: "Official BYD partner in Albania with up to 6-year warranty; offers custom orders and full support", image_url: "https://picsum.photos/seed/connect-drive/800/600", isFeatured: true },
    { id: "2", name: "Albanian Motor Company (Hyundai)", address: "Autostrada Tiranë – Durrës, Km 2, Mëzez, Tiranë", city: "Tirana", lat: 41.3315, lng: 19.7788, phone: "+355 67 40 44 406", website: "https://www.hyundai.al", social_links: { instagram: "@hyundaimotors.albania", facebook: "Facebook" }, brands: ["Hyundai"], modelsAvailable: ["Kona Electric", "IONIQ 5", "IONIQ 6", "Tucson Hybrid"], typeOfCars: "New", languages: ["Albanian", "English"], notes: "Official Hyundai dealer; provides sales, service and test drives; 5-year warranty. Service phone: +355 67 55 22 285", image_url: "https://picsum.photos/seed/albanian-motor/800/600", isFeatured: true },
    { id: "3", name: "MG Motor Albania", address: "Auto. Tirana – Durres, Km 10, Kashar, Tirana", city: "Tirana", lat: 41.3488, lng: 19.7186, phone: "+355 69 440 1111", email: "mg@grandautomotive.hr", website: "https://www.mgmotor.al", social_links: { instagram: "@mgmotoralbania", facebook: "Facebook" }, brands: ["MG Motor"], modelsAvailable: ["MG ZS EV", "MG 4", "MG 5", "MG Marvel R", "MG EHS"], typeOfCars: "New", languages: ["Albanian", "English"], notes: "Part of Albanian Motor Company; sells electric and hybrid MG models", image_url: "https://picsum.photos/seed/mg-motor/800/600", isFeatured: true },
    { id: "4", name: "iDrive", address: "Rruga e Kavajes, nd. 4, h. nr 26, Tirane", city: "Tirana", lat: 41.3259, lng: 19.8142, phone: "+355 69 70 22 802", email: "gimitushka@yahoo.com", website: "", social_links: { instagram: "@idrive_eev", facebook: "Facebook" }, brands: ["Various EV Brands"], modelsAvailable: ["Varies (imports EVs on demand)"], typeOfCars: "New and used", languages: ["Albanian"], notes: "Importer and reseller of electric vehicles; sells EVs through social media and classifieds. WhatsApp: +355 69 70 22 802, Other phone: +355 69 702 3002", image_url: "https://picsum.photos/seed/idrive/800/600", isFeatured: true },
    { id: "5", name: "Mechatronic Auto", address: "Kashar, Albania", city: "Tirana", lat: 41.3545, lng: 19.7305, phone: "+355 69 10 00 00", email: "info@mechatronicauto.al", website: "https://mechatronicauto.al", social_links: { instagram: "@mechatronicauto_al", facebook: "Facebook" }, brands: ["BYD", "AutoEV"], modelsAvailable: ["BYD Dolphin", "AutoEV R200", "AutoEV R300", "and other EVs"], typeOfCars: "New", languages: ["Albanian", "English"], notes: "Provides EV sales, service and charging solutions; sells electric cars and scooters. Other phone: +355 69 10 00 01", image_url: "https://picsum.photos/seed/mechatronic-auto/800/600" },
    { id: "6", name: "ECA Electric Cars Albania", address: "Autostrada Tiranë-Elbasan KM.2 (TEG-Tiranë, Godina Park Place)", city: "Tirana", lat: 41.3168, lng: 19.8973, phone: "+355 67 40 23 808", email: "info@eca.al", website: "https://eca.al", social_links: { instagram: "@electric_cars_albania", facebook: "Facebook", twitter: "Twitter", youtube: "YouTube" }, brands: ["Tesla", "Toyota", "Honda", "Volkswagen", "SRM", "GEAK"], modelsAvailable: ["Honda e-NS1", "VW ID.3 Pure", "VW ID.4 Pro Performance", "VW ID.6 Pro Performance", "Toyota BZ4X", "Tesla Model Y Dual Motor", "SRM Van"], typeOfCars: "New", languages: ["Albanian", "English"], notes: "Showroom near TEG; test drive booking available; chargers and services", image_url: "https://picsum.photos/seed/eca-electric/800/600" },
    { id: "7", name: "Tirana Electric Motors", address: "Autostrada Tiranë – Durrës KM.5", city: "Tirana", lat: 41.3399, lng: 19.7479, phone: "+355 69 20 63 834", website: "https://tiranaelectricmotors.com", social_links: { instagram: "Tirana Electric Motors", twitter: "Twitter", youtube: "YouTube" }, brands: ["Neta Auto", "BYD", "Volkswagen", "Maxus", "Audi", "Xpeng"], modelsAvailable: ["BYD Song Plus", "BYD Yuan Plus", "BYD Tang L", "Volkswagen ID.3 Pure Long Range", "Volkswagen ID.6 X Pro", "Maxus Dana V1", "Audi Q4 e-Tron", "Xpeng G9", "BYD Sealion 07"], typeOfCars: "New", languages: ["Albanian", "English"], priceRange: "€18,999–33,999", notes: "Official distributor of Neta Auto; provides charging stations and technical assistance", image_url: "https://picsum.photos/seed/tirana-electric/800/600" },
    { id: "8", name: "Panda Electric Motors", address: "Fshati Mëzez, Njësia Administrative Kashar, Tiranë", city: "Tirana", lat: 41.3325, lng: 19.7616, phone: "+355 68 902 5777", email: "ebegaj3@gmail.com", website: "N/A", social_links: { instagram: "@panda_electric_motors", facebook: "Facebook" }, brands: ["BYD", "Aion", "Zeekr"], modelsAvailable: ["BYD Tang", "BYD Yuan Plus", "Aion V", "Aion Y"], typeOfCars: "New", languages: ["Albanian"], notes: "Specializes in importing new EVs with 0 km; offers service and parts. Former website: pe-motors.com", image_url: "https://picsum.photos/seed/panda-electric/800/600" },
    { id: "9", name: "AutoEuropa", address: "Autostrada Km 5, Durrës – Tiranë, Durrës 2019, Albania (Sukth)", city: "Durrës", lat: 41.3508, lng: 19.5397, phone: "+355 69 700 6655", email: "info@autoeuropa.com.al", website: "https://autoeuropa.com.al", social_links: { facebook: "AutoEuropa", instagram: "Instagram" }, brands: ["Volkswagen"], modelsAvailable: ["Volkswagen ID.4 Pro", "Volkswagen ID.6 Pro", "Volkswagen ID.3 Pure"], typeOfCars: "New and Used", languages: ["Albanian", "English"], priceRange: "€27,900–46,900", notes: "Showroom in Sukth near Durrës; 24/7 customer support", image_url: "https://picsum.photos/seed/autoeuropa/800/600" },
    { id: "10", name: "Go Electric Albania", address: "Rruga Dervish Hima 3, Kullat, Kulla Nr 3, Kati 1, Tirana", city: "Tirana", lat: 41.3225, lng: 19.8187, phone: "+355 67 208 3625", email: "gfc_al@yahoo.com", website: "N/A", social_links: { instagram: "@goelectric_albania", facebook: "Facebook" }, brands: ["BYD", "Avatr", "Zeekr", "Denza"], modelsAvailable: ["Denza N8", "Avatr 12", "BYD Sealion"], typeOfCars: "New", languages: ["Albanian"], notes: "Provides 5-year/100,000 km warranty on vehicles; imports and sells EVs. Other email: xhorxhidusha@icloud.com", image_url: "https://picsum.photos/seed/go-electric/800/600" },
    { id: "11", name: "SENA EV SH.P.K", address: "Qerekë, Krujë", city: "Krujë", lat: 41.4883, lng: 19.7153, phone: "+355 69 347 3384", email: "senaelectricvehicle@gmail.com", website: "http://www.senaelectricvehicle.al", social_links: { instagram: "@sena.electricvehicle", facebook: "Facebook" }, brands: ["BYD", "Avatr", "Aion"], modelsAvailable: ["BYD Song L", "BYD Sealion", "Avatr", "Aion series"], typeOfCars: "New", languages: ["Albanian"], notes: "Offers vehicles by order; provides maintenance and repair services", image_url: "https://picsum.photos/seed/sena-ev/800/600" },
    { id: "12", name: "Electric Vehicle Albania (EVA)", address: "Rruga Pjeter Bogdani, Lagja 14, Yzberish, Tirana 1050", city: "Tirana", lat: 41.3175, lng: 19.7891, phone: "+355 69 581 0531", email: "electricvehiclealbania@gmail.com", website: "", social_links: { instagram: "@eva_auto_electric_albania", facebook: "Facebook" }, brands: ["BYD", "Aion", "Zeekr", "Hozon"], modelsAvailable: ["BYD G9 Max", "Zeekr X", "Aion V Pro", "Aion Y Plus", "BYD Song Plus", "BYD Yuan Plus"], typeOfCars: "New", languages: ["Albanian"], notes: "Sells 100% electric cars with 0 km; offers WhatsApp contact for quotes", image_url: "https://picsum.photos/seed/eva-albania/800/600" },
];

export const initialModels: Model[] = [
    { id: "1", brand: "Honda", model_name: "e:Ny1 (e:NS1)", body_type: "Compact SUV", battery_capacity: 68.8, range_wltp: 412, power_kw: 150, torque_nm: 310, acceleration_0_100: 7.6, top_speed: 160, drive_type: "FWD", seats: 5, charging_ac: "11 kW", charging_dc: "150 kW", image_url: 'https://picsum.photos/seed/honda-eny1/800/600', isFeatured: true },
    { id: "2", brand: "Volkswagen", model_name: "ID.3 Pro", body_type: "Hatchback", battery_capacity: 62, range_wltp: 429, power_kw: 150, torque_nm: 310, acceleration_0_100: 7.3, top_speed: 160, drive_type: "RWD", seats: 5, charging_ac: "11 kW", charging_dc: "120 kW", image_url: 'https://picsum.photos/seed/vw-id3/800/600', isFeatured: true },
    { id: "3", brand: "Volkswagen", model_name: "ID.4 Pro", body_type: "Mid-size SUV", battery_capacity: 82, range_wltp: 574, power_kw: 210, torque_nm: 545, acceleration_0_100: 6.7, top_speed: 180, drive_type: "AWD", seats: 5, charging_ac: "11 kW", charging_dc: "175 kW", image_url: 'https://picsum.photos/seed/vw-id4/800/600', isFeatured: true },
    { id: "4", brand: "Volkswagen", model_name: "ID.6 X Pro", body_type: "Large SUV", battery_capacity: 83.4, range_wltp: 588, power_kw: 152, acceleration_0_100: 6.6, top_speed: 160, drive_type: "AWD", seats: 7, image_url: 'https://picsum.photos/seed/vw-id6/800/600', isFeatured: true },
    { id: "5", brand: "Toyota", model_name: "bZ4X AWD", body_type: "Compact SUV", battery_capacity: 71.4, range_wltp: 461, power_kw: 160, torque_nm: 336, acceleration_0_100: 6.9, top_speed: 160, drive_type: "AWD", seats: 5, charging_ac: "11 kW", charging_dc: "150 kW", image_url: 'https://picsum.photos/seed/toyota-bz4x/800/600' },
    { id: "6", brand: "Tesla", model_name: "Model Y Long Range AWD", body_type: "Mid-size SUV", battery_capacity: 78.1, range_wltp: 542, power_kw: 378, torque_nm: 493, acceleration_0_100: 5, top_speed: 217, drive_type: "AWD", seats: 5, charging_ac: "11 kW", charging_dc: "250 kW", image_url: 'https://picsum.photos/seed/tesla-y/800/600' },
    { id: "7", brand: "BYD", model_name: "Atto 3 (Yuan Plus)", body_type: "Compact SUV", battery_capacity: 60.5, range_wltp: 420, power_kw: 150, torque_nm: 310, acceleration_0_100: 7.3, top_speed: 160, drive_type: "FWD", seats: 5, charging_ac: "6.6 kW", charging_dc: "80 kW", image_url: 'https://picsum.photos/seed/byd-atto3/800/600' },
    { id: "8", brand: "BYD", model_name: "Dolphin", body_type: "Hatchback", battery_capacity: 60.4, range_wltp: 427, power_kw: 150, torque_nm: 310, acceleration_0_100: 7, top_speed: 160, drive_type: "FWD", seats: 5, charging_dc: "88 kW", image_url: 'https://picsum.photos/seed/byd-dolphin/800/600' },
    { id: "9", brand: "BYD", model_name: "Han EV", body_type: "Luxury Sedan", battery_capacity: 85.4, range_wltp: 521, power_kw: 380, torque_nm: 700, acceleration_0_100: 3.9, top_speed: 180, drive_type: "AWD", seats: 5, charging_ac: "7 kW", charging_dc: "120 kW", image_url: 'https://picsum.photos/seed/byd-han/800/600' },
    { id: "10", brand: "Zeekr", model_name: "X Privilege AWD", body_type: "Compact SUV", battery_capacity: 69, range_wltp: 400, power_kw: 315, torque_nm: 543, acceleration_0_100: 3.8, top_speed: 180, drive_type: "AWD", seats: 5, charging_dc: "150 kW", image_url: 'https://picsum.photos/seed/zeekr-x/800/600' },
    { id: "11", brand: "Hyundai", model_name: "Kona Electric", body_type: "Compact SUV", battery_capacity: 68.5, range_wltp: 514, power_kw: 160, torque_nm: 255, acceleration_0_100: 7.8, top_speed: 170, drive_type: "FWD", seats: 5, charging_ac: "11 kW", charging_dc: "105 kW", image_url: 'https://picsum.photos/seed/hyundai-kona/800/600' },
    { id: "12", brand: "Hyundai", model_name: "IONIQ 5", body_type: "Crossover SUV", battery_capacity: 84, range_wltp: 570, power_kw: 168, torque_nm: 350, acceleration_0_100: 7.5, top_speed: 185, drive_type: "RWD", seats: 5, charging_ac: "11 kW", charging_dc: "263 kW", image_url: 'https://picsum.photos/seed/hyundai-ioniq5/800/600' },
    { id: "13", brand: "Hyundai", model_name: "IONIQ 6", body_type: "Sedan", battery_capacity: 77.4, range_wltp: 614, power_kw: 168, torque_nm: 350, acceleration_0_100: 7.4, top_speed: 185, drive_type: "RWD", seats: 5, charging_ac: "11 kW", charging_dc: "233 kW", image_url: 'https://picsum.photos/seed/hyundai-ioniq6/800/600' },
    { id: "14", brand: "MG Motor", model_name: "MG ZS EV", body_type: "Compact SUV", battery_capacity: 72.6, range_wltp: 440, power_kw: 115, torque_nm: 280, acceleration_0_100: 8.4, top_speed: 175, drive_type: "FWD", seats: 5, charging_ac: "7.4 kW", charging_dc: "94 kW", image_url: 'https://picsum.photos/seed/mg-zs/800/600' },
    { id: "15", brand: "MG Motor", model_name: "MG 4", body_type: "Hatchback", battery_capacity: 64, range_wltp: 450, power_kw: 150, torque_nm: 250, acceleration_0_100: 7.9, top_speed: 160, drive_type: "RWD", seats: 5, charging_ac: "6.6 kW", charging_dc: "142 kW", image_url: 'https://picsum.photos/seed/mg-4/800/600' },
    { id: "16", brand: "Hyundai", model_name: "Tucson Plug-in Hybrid", body_type: "Compact SUV (PHEV)", battery_capacity: 13.8, range_wltp: 56, power_kw: 195, torque_nm: 350, acceleration_0_100: null, top_speed: 191, drive_type: "AWD", seats: 5, charging_ac: "7.2 kW", charging_dc: null, image_url: 'https://picsum.photos/seed/hyundai-tucson-phev/800/600' },
    { id: "17", brand: "AutoEV", model_name: "R200", body_type: "Electric Scooter", battery_capacity: null, range_wltp: 130, power_kw: 3.5, torque_nm: null, acceleration_0_100: null, top_speed: 100, drive_type: "Electric two-wheeler", seats: 2, charging_ac: "Unknown", charging_dc: null, image_url: 'https://picsum.photos/seed/autoev-r200/800/600' },
    { id: "18", brand: "AutoEV", model_name: "RX200", body_type: "Electric Scooter", battery_capacity: null, range_wltp: 150, power_kw: 4, torque_nm: null, acceleration_0_100: null, top_speed: 120, drive_type: "Electric two-wheeler", seats: 2, charging_ac: "Unknown", charging_dc: null, image_url: 'https://picsum.photos/seed/autoev-rx200/800/600' },
    { id: "19", brand: "Maxus", model_name: "Dana V1", body_type: "Electric Van", battery_capacity: 51, range_wltp: 350, power_kw: 122, torque_nm: null, acceleration_0_100: null, top_speed: 100, drive_type: "FWD", seats: 2, charging_ac: null, charging_dc: "80% in 45 min", image_url: 'https://picsum.photos/seed/maxus-dana-v1/800/600' },
    { id: "20", brand: "BYD", model_name: "Sealion 07", body_type: "Mid-size SUV", battery_capacity: 82.5, range_wltp: 456, power_kw: 390, torque_nm: 690, acceleration_0_100: 4.5, top_speed: 215, drive_type: "AWD", seats: 5, charging_ac: "11 kW", charging_dc: "150 kW", image_url: 'https://picsum.photos/seed/byd-sealion07/800/600' },
    { id: "21", brand: "BYD", model_name: "Seagull (Long Range)", body_type: "City Hatchback", battery_capacity: 38.88, range_wltp: 405, power_kw: 55, torque_nm: 135, acceleration_0_100: null, top_speed: 130, drive_type: "FWD", seats: 5, charging_ac: "6.6 kW", charging_dc: "40 kW", image_url: 'https://picsum.photos/seed/byd-seagull/800/600' },
    { id: "22", brand: "BYD", model_name: "Seal (RWD)", body_type: "Mid-size Sedan", battery_capacity: 82.5, range_wltp: 570, power_kw: 230, torque_nm: 360, acceleration_0_100: 5.9, top_speed: 180, drive_type: "RWD", seats: 5, charging_ac: "11 kW", charging_dc: "150 kW", image_url: 'https://picsum.photos/seed/byd-seal-rwd/800/600' },
    { id: "23", brand: "BYD", model_name: "Seal (AWD)", body_type: "Mid-size Sedan", battery_capacity: 82.5, range_wltp: 520, power_kw: 390, torque_nm: 670, acceleration_0_100: 3.8, top_speed: 180, drive_type: "AWD", seats: 5, charging_ac: "11 kW", charging_dc: "150 kW", image_url: 'https://picsum.photos/seed/byd-seal-awd/800/600' },
    { id: "24", brand: "Xpeng", model_name: "G9 AWD Long Range", body_type: "Mid-size SUV", battery_capacity: 98, range_wltp: 520, power_kw: 405, torque_nm: 717, acceleration_0_100: 3.9, top_speed: 200, drive_type: "AWD", seats: 5, charging_ac: "11 kW", charging_dc: "300 kW", image_url: 'https://picsum.photos/seed/xpeng-g9/800/600' },
    { id: "25", brand: "MG Motor", model_name: "MG5 EV Long Range", body_type: "Estate/Wagon", battery_capacity: 61.1, range_wltp: 400, power_kw: 115, torque_nm: 280, acceleration_0_100: 7.7, top_speed: 185, drive_type: "FWD", seats: 5, charging_ac: "11 kW", charging_dc: "87 kW", image_url: 'https://picsum.photos/seed/mg-5/800/600' },
    { id: "26", brand: "MG Motor", model_name: "Marvel R Performance", body_type: "Compact SUV", battery_capacity: 75, range_wltp: 370, power_kw: 212, torque_nm: 665, acceleration_0_100: 4.9, top_speed: 200, drive_type: "Tri-motor AWD", seats: 5, charging_ac: "11 kW", charging_dc: "94 kW", image_url: 'https://picsum.photos/seed/mg-marvel-r/800/600' },
    { id: "27", brand: "MG Motor", model_name: "EHS Plug-in Hybrid", body_type: "Compact SUV (PHEV)", battery_capacity: 16.6, range_wltp: 52, power_kw: 190, torque_nm: 370, acceleration_0_100: 6.9, top_speed: 190, drive_type: "FWD", seats: 5, charging_ac: "3.7 kW", charging_dc: null, image_url: 'https://picsum.photos/seed/mg-ehs-phev/800/600' },
    { id: "28", brand: "SRM", model_name: "T3L EV", body_type: "Cargo Van", battery_capacity: 42, range_wltp: 290, power_kw: 60, torque_nm: null, acceleration_0_100: null, top_speed: 80, drive_type: "FWD", seats: 2, charging_ac: "Inaccurate", charging_dc: null, image_url: 'https://picsum.photos/seed/srm-t3l/800/600' },
    { id: "29", brand: "BYD", model_name: "Tang AWD", body_type: "Full-size SUV", battery_capacity: 89, range_wltp: 400, power_kw: 380, torque_nm: 680, acceleration_0_100: 4.6, top_speed: 180, drive_type: "AWD", seats: 7, charging_ac: "7.4 kW", charging_dc: "110 kW", image_url: 'https://picsum.photos/seed/byd-tang/800/600' },
    { id: "30", brand: "BYD", model_name: "Song Plus EV", body_type: "Mid-size SUV", battery_capacity: 71.7, range_wltp: 505, power_kw: 137, torque_nm: 280, acceleration_0_100: 7.7, top_speed: 180, drive_type: "FWD", seats: 5, charging_ac: "6.6 kW", charging_dc: "90 kW", image_url: 'https://picsum.photos/seed/byd-song-plus/800/600' },
    { id: "31", brand: "BYD", model_name: "Song L", body_type: "Large Hatchback/SUV", battery_capacity: 87, range_wltp: 662, power_kw: 386, torque_nm: null, acceleration_0_100: 4.3, top_speed: 201, drive_type: "AWD", seats: 5, charging_ac: null, charging_dc: null, image_url: 'https://picsum.photos/seed/byd-song-l/800/600' },
    { id: "32", brand: "GAC Aion", model_name: "Y Plus", body_type: "Compact MPV/SUV", battery_capacity: 63, range_wltp: 610, power_kw: 150, torque_nm: null, acceleration_0_100: 8.5, top_speed: 150, drive_type: "FWD", seats: 5, charging_ac: null, charging_dc: "80 kW", image_url: 'https://picsum.photos/seed/gac-aion-y-plus/800/600' },
    { id: "33", brand: "GAC Aion", model_name: "V", body_type: "Compact SUV", battery_capacity: 72.3, range_wltp: 600, power_kw: 135, torque_nm: null, acceleration_0_100: null, top_speed: 175, drive_type: "FWD", seats: 5, charging_ac: "Unknown", charging_dc: null, image_url: 'https://picsum.photos/seed/gac-aion-v/800/600' },
    { id: "34", brand: "Denza", model_name: "N8 PHEX", body_type: "Luxury SUV (PHEV)", battery_capacity: 45.8, range_wltp: 216, power_kw: 360, torque_nm: 675, acceleration_0_100: 4.3, top_speed: 190, drive_type: "AWD (PHEV)", seats: 7, charging_ac: null, charging_dc: "90 kW", image_url: 'https://picsum.photos/seed/denza-n8/800/600' },
    { id: "35", brand: "Avatr", model_name: "12 RWD", body_type: "Executive Sedan", battery_capacity: 94.5, range_wltp: 700, power_kw: 230, torque_nm: 370, acceleration_0_100: 6.7, top_speed: 215, drive_type: "RWD", seats: 5, charging_ac: "Unknown", charging_dc: null, image_url: 'https://picsum.photos/seed/avatr-12-rwd/800/600' },
    { id: "36", brand: "Avatr", model_name: "12 AWD", body_type: "Executive Sedan", battery_capacity: 94.5, range_wltp: 650, power_kw: 425, torque_nm: 650, acceleration_0_100: 3.9, top_speed: 220, drive_type: "AWD", seats: 5, charging_ac: "Unknown", charging_dc: null, image_url: 'https://picsum.photos/seed/avatr-12-awd/800/600' }
];

// Inferred many-to-many relationships
export const initialDealerModels: DealerModel[] = [
    // Connect Drive (id: 1)
    { dealer_id: "1", model_id: "7" }, { dealer_id: "1", model_id: "8" }, { dealer_id: "1", model_id: "9" }, { dealer_id: "1", model_id: "20" }, { dealer_id: "1", model_id: "21" }, { dealer_id: "1", model_id: "30" },
    // Albanian Motor Company (id: 2)
    { dealer_id: "2", model_id: "11" }, { dealer_id: "2", model_id: "12" }, { dealer_id: "2", model_id: "13" }, { dealer_id: "2", model_id: "16" },
    // MG Motor Albania (id: 3)
    { dealer_id: "3", model_id: "14" }, { dealer_id: "3", model_id: "15" }, { dealer_id: "3", model_id: "25" }, { dealer_id: "3", model_id: "26" }, { dealer_id: "3", model_id: "27" },
    // iDrive (id: 4) - no specific models
    // Mechatronic Auto (id: 5)
    { dealer_id: "5", model_id: "8" }, { dealer_id: "5", model_id: "17" }, { dealer_id: "5", model_id: "18" },
    // ECA Electric Cars (id: 6)
    { dealer_id: "6", model_id: "1" }, { dealer_id: "6", model_id: "2" }, { dealer_id: "6", model_id: "3" }, { dealer_id: "6", model_id: "4" }, { dealer_id: "6", model_id: "5" }, { dealer_id: "6", model_id: "6" }, { dealer_id: "6", model_id: "28" },
    // Tirana Electric Motors (id: 7)
    { dealer_id: "7", model_id: "7" }, { dealer_id: "7", model_id: "20" }, { dealer_id: "7", model_id: "24" }, { dealer_id: "7", model_id: "29" }, { dealer_id: "7", model_id: "30" }, { dealer_id: "7", model_id: "2" }, { dealer_id: "7", model_id: "4" }, { dealer_id: "7", model_id: "19" },
    // Panda Electric Motors (id: 8)
    { dealer_id: "8", model_id: "7" }, { dealer_id: "8", model_id: "29" }, { dealer_id: "8", model_id: "32" }, { dealer_id: "8", model_id: "33" },
    // AutoEuropa (id: 9)
    { dealer_id: "9", model_id: "2" }, { dealer_id: "9", model_id: "3" }, { dealer_id: "9", model_id: "4" },
    // Go Electric Albania (id: 10)
    { dealer_id: "10", model_id: "20" }, { dealer_id: "10", model_id: "34" }, { dealer_id: "10", model_id: "35" }, { dealer_id: "10", model_id: "36" },
    // SENA EV SH.P.K (id: 11)
    { dealer_id: "11", model_id: "20" }, { dealer_id: "11", model_id: "31" }, { dealer_id: "11", model_id: "32" }, { dealer_id: "11", model_id: "33" }, { dealer_id: "11", model_id: "35" }, { dealer_id: "11", model_id: "36" },
    // Electric Vehicle Albania (EVA) (id: 12)
    { dealer_id: "12", model_id: "7" }, { dealer_id: "12", model_id: "10" }, { dealer_id: "12", model_id: "24" }, { dealer_id: "12", model_id: "30" }, { dealer_id: "12", model_id: "32" }, { dealer_id: "12", model_id: "33" },
];

export const blogPosts: BlogPost[] = [
  { id: '1', title: 'Makina Elektrike vs. Makinë me Djegie të Brendshme: Cila Është Zgjedhja e Duhur për Ju?', excerpt: 'Një krahasim i thelluar i kostove, performancës dhe ndikimit mjedisor për t\'ju ndihmuar të merrni një vendim të informuar.', author: 'Admin', date: '2024-07-20', imageUrl: 'https://picsum.photos/seed/blog1/800/400' },
  { id: '2', title: '5 Mite Rreth Makinave Elektrike që Duhet t\'i Harroni', excerpt: 'Nga "ankthi i autonomisë" te kostot e larta, ne rrëzojmë keqkuptimet më të zakonshme rreth automjeteve elektrike.', author: 'Admin', date: '2024-07-15', imageUrl: 'https://picsum.photos/seed/blog2/800/400' },
  { id: '3', title: 'Si të Zgjidhni Stacionin e Duhur të Karikimit në Shtëpi?', excerpt: 'Një udhëzues praktik për llojet e ndryshme të karikuesve, shpejtësitë e karikimit dhe çfarë duhet të keni parasysh para instalimit.', author: 'Admin', date: '2024-07-10', imageUrl: 'https://picsum.photos/seed/blog3/800/400' },
  { id: '4', title: 'Top 7 Makinat Elektrike më të Përshtatshme për Familjet në Shqipëri', excerpt: 'Po kërkoni një EV të gjerë, të sigurt dhe efikas? Këtu janë zgjedhjet tona kryesore që mund t\'i gjeni në tregun shqiptar.', author: 'Admin', date: '2024-07-05', imageUrl: 'https://picsum.photos/seed/blog4/800/400' }
];

const simulateDelay = <T,>(data: T): Promise<T> =>
  new Promise(resolve => setTimeout(() => resolve(data), 500));

export const getDealers = () => simulateDelay(initialDealers);
export const getModels = () => simulateDelay(initialModels);

export const getDealerById = (id: string) => 
  simulateDelay(initialDealers.find(d => d.id === id));

export const getModelById = (id: string) => 
  simulateDelay(initialModels.find(m => m.id === id));

export const getModelsByDealerId = (dealerId: string) => {
    const modelIds = initialDealerModels
        .filter(dm => dm.dealer_id === dealerId)
        .map(dm => dm.model_id);
    const models = initialModels.filter(m => modelIds.includes(m.id));
    return simulateDelay(models);
};

export const getDealersByModelId = (modelId: string) => {
    const dealerIds = initialDealerModels
        .filter(dm => dm.model_id === modelId)
        .map(dm => dm.dealer_id);
    const dealers = initialDealers.filter(d => dealerIds.includes(d.id));
    return simulateDelay(dealers);
};
  
export const getBlogPosts = () => simulateDelay(blogPosts);